DROP TABLE MEDICINE;

CREATE TABLE MEDICINE(
    MED_NAME VARCHAR2(50) NOT NULL,
    MEDICINE VARCHAR2(50) PRIMARY KEY,
    FORMULATION VARCHAR2(80) NOT NULL,
    MED_TARGET VARCHAR2(80) NOT NULL,
    MED_NO NUMBER NOT NULL,
    PROD_COST NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    INVEN NUMBER DEFAULT 0
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 COMMENT ON COLUMN MEDICINE.MED_NAME IS '약품학명';
 COMMENT ON COLUMN MEDICINE.MEDICINE IS '제품이름';
 COMMENT ON COLUMN MEDICINE.FORMULATION IS '제형';
 COMMENT ON COLUMN MEDICINE.MED_TARGET IS '타겟 질병';
 COMMENT ON COLUMN MEDICINE.MED_NO IS '약품번호';
 COMMENT ON COLUMN MEDICINE.PROD_COST IS '생산 비용';
 COMMENT ON COLUMN MEDICINE.PRICE IS '가격';
 COMMENT ON COLUMN MEDICINE.INVEN IS '재고수량';
 
SET DEFINE OFF;
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Hexoprenaline','이피라돌정','화학의약품, 0.5mg','천식, 기관지, 진폐증', 222, 1600, 2500, 65);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Ciltacabtagene Autoleucel','카빅티주','바이오시밀러, 10^6cells/ml','재발, 불응성 다발골수종',422,2600000,2600000,5);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Purified Influenza Virus Antigen A','그린플루에스','백신, 1ml','신종인플루엔자A',631,160000,160000,30);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Basiliximab','씨뮬렉트','바이오시밀러 20mg','급성 장기 거부반응 억제',142,600000,600000,34);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Balsalazide Disodium Hydrate','콜라잘캡슐','화학의약품, 750mg','위염, 대장염',238,1700,1700,42);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Aspirin','아스피린장용','화학의약품, 100mg','심혈관계 혈전생성 억제',219,500,500,128);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Mefloquine Hydrochloride','라리암정','화학의약품, 250mg','말라리아',641,1500,1500,249);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Pinaverium Bromide','디스텐정','화학의약품, 50mg','과민성 대장증후군',239,1300,1300,76);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('lxekizumab','탈츠오토인젝터','바이오시밀러, 1ml','강직성 척추염, 건선',141,800000,800000,33);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Ani-D Immunogobulin','윈로에스디에프','유전자치료제, 3ml','혈소판 감소 자반증',634,90000,90000,67);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Cladribine','류스타틴','유전자치료제, 1mg/ml','백혈병',421,240000,240000,11);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Dimethicone','그루타제정','화학의약품, 25mg','소화불량, 식욕감퇴, 급체, 과식',233,600,600,168);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Atezolizumab','티쎈트릭','바이오시밀러, 20ml','비소세포폐암, 간세포암, 삼중음성유방암',420,1600000,1600000,16);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('insulin Aspart','노보래피드','유전자치료제, 100U/ml','당뇨, 다이어트',396,12000,12000,34);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Mepivaiacine Hydrochloride','화학의약품, 5ml','메카바주','침윤마취',121,200000,200000,50);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Human Papilloma VirusL1 Protein','가다실9주','백신, 20ug','자궁경부암, 항문암, 항문상피종양',632,780000,780000,48);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('DL-Methylephedrine Hydrochloride','네오콜코프','화학의약품, 8mg','감기, 두통, 근육통',114,1500,1500,36);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Ampicillin','암피신캡슐','화학의약품, 250mg','향균제',618,1100,1100,82);
INSERT INTO MEDICINE (MED_NAME,MEDICINE,FORMULATION,MED_TARGET,MED_NO,PROD_COST,PRICE,INVEN)
VALUES ('Varicella Zoster Virus protein','싱그릭스','백신, 50ug','대상포진',633,750000,750000,3);

--------------------------------------------------------
--  Constraints for Table ORDER
--------------------------------------------------------
DROP TABLE MED_ORDER;

CREATE TABLE MED_ORDER(
    MEDICINE VARCHAR2(50) REFERENCES MEDICINE(MEDICINE) NOT NULL ,
    FORMULATION VARCHAR2(100) NOT NULL,
    MED_NO NUMBER NOT NULL,
    ORDER_NO CHAR(10) PRIMARY KEY,
    QUANTITY NUMBER NOT NULL,
    ORDER_NAME VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2 (100) NOT NULL,
    PHONE CHAR(13) NOT NULL
    
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
 COMMENT ON COLUMN MED_ORDER.ORDER_NO IS '주문번호';
  COMMENT ON COLUMN MED_ORDER.MEDICINE IS '주문약품';
 COMMENT ON COLUMN MED_ORDER.QUANTITY IS '주문수량';
 COMMENT ON COLUMN MED_ORDER.ORDER_NAME IS '주문자 이름';
 COMMENT ON COLUMN MED_ORDER.ADDRESS IS '주문자 주소';
 COMMENT ON COLUMN MED_ORDER.PHONE IS '주문자 전화번호';
 COMMENT ON COLUMN MED_ORDER.FORMULATION IS '제형';
 COMMENT ON COLUMN MED_ORDER.MED_NO IS '약품번호';
 
SET DEFINE OFF;
INSERT INTO MED_ORDER
VALUES ('카빅티주','바이오시밀러, 10^6cells/ml',422,'O11msC0J1d',15,'양민욱','동작','010-3569-4586');
INSERT INTO MED_ORDER 
VALUES ('이피라돌정','화학의약품, 0.5mg',222,'O70dwT1G0z',3,'김정현','판교','010-1234-5678');
INSERT INTO MED_ORDER
VALUES ('티쎈트릭','바이오시밀러, 20ml',420,'O85rjY4R6v',7,'이요셉','대치','010-9845-1123');
INSERT INTO MED_ORDER
VALUES ('그루타제정','화학의약품, 25mg',233,'O56pzA7Q8u',4,'정은유','종로','010-6528-4612');
INSERT INTO MED_ORDER
VALUES ('싱그릭스','백신, 50ug',633,'O70ueW5R3a',40,'최서은','동대문','010-8524-3214');
INSERT INTO MED_ORDER
VALUES ('카빅티주','바이오시밀러, 10^6cells/ml',422,'O19sxO9Z1q',10,'조건웅','양평','010-1234-1111');
INSERT INTO MED_ORDER
VALUES ('류스타틴','유전자치료제, 1mg/ml',421,'O56qxE8D4s',15,'이혜인','사당','010-1231-2222');
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------
DROP TABLE CUSTOMER ;

CREATE TABLE CUSTOMER (
    CUS_NAME VARCHAR2(15) NOT NULL,
    CUS_ID VARCHAR2(15) PRIMARY KEY, -- 아이디는 15글자 제한
    CUS_PWD VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2 (100),
    PHONE CHAR(13)    
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  COMMENT ON COLUMN CUSTOMER.CUS_NAME IS '고객 이름';
  COMMENT ON COLUMN CUSTOMER.CUS_ID IS '아이디';
  COMMENT ON COLUMN CUSTOMER.CUS_PWD IS '비밀번호';
  COMMENT ON COLUMN CUSTOMER.ADDRESS IS '주소';
  COMMENT ON COLUMN CUSTOMER.PHONE IS '전화번호';
  
SET DEFINE OFF;
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('양민욱', 'civilAngar', '1234', '동작', '010-1111-2222');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('김정현', 'inLine', '1234', '판교', '010-4444-3333');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('이요셉', 'doubleJoseb', '1234', '대치', '010-1555-5555');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('정은유', 'rightDiscribe', '1234', '종로', '010-9999-8888');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('최서은', 'westSilver', '1234', '동대문', '010-6766-7887');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('조건웅', 'if(true)', '1234', '양평', '010-1595-2595');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('이혜인', 'understandIn', '1234', '사당', '010-1234-1595');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('허 완', 'fakeFinish', '1234', '구리', '010-7458-9955');
INSERT INTO CUSTOMER (CUS_NAME, CUS_ID, CUS_PWD, ADDRESS, PHONE)
VALUES('최원탁', 'tableChoice', '1234', '인천', '010-4444-5444');


--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
    EMP_NO CHAR(3) PRIMARY KEY,
    EMP_NAME VARCHAR2(15) NOT NULL,
    EMP_ID VARCHAR2(15) NOT NULL UNIQUE,
    EMP_PWD VARCHAR2(15) NOT NULL,
    GENDER CHAR(3),
    ADDRESS VARCHAR2(300),
    PHONE VARCHAR2(13),
    DEPT VARCHAR2(20),
    SALARY NUMBER,
    BONUS NUMBER
)SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '사원번호';
  COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '사원이름';
  COMMENT ON COLUMN EMPLOYEE.EMP_ID IS '아이디';
  COMMENT ON COLUMN EMPLOYEE.EMP_PWD IS '비밀번호';
  COMMENT ON COLUMN EMPLOYEE.GENDER IS '성별';
  COMMENT ON COLUMN EMPLOYEE.PHONE IS '주소';
  COMMENT ON COLUMN EMPLOYEE.PHONE IS '전화번호';
  COMMENT ON COLUMN EMPLOYEE.DEPT IS '부서';
  COMMENT ON COLUMN EMPLOYEE.SALARY IS '월급';
  COMMENT ON COLUMN EMPLOYEE.BONUS IS '보너스';
  
SET DEFINE OFF;
INSERT INTO EMPLOYEE
VALUES('000','엄희윤','0a','a1234','남','잠실','010-7440-****','임원',NULL,NULL);
INSERT INTO EMPLOYEE
VALUES('206','양준혁','hGiveSheep','a1234',NULL,'평택','010-1234-5678','생산',2300000,0.005);
INSERT INTO EMPLOYEE
VALUES('207','임현호','tigerLine','a1234',NULL,NULL,NULL,'생산',2300000,0.005);
INSERT INTO EMPLOYEE
VALUES('778','최재영','reZero','a1234',NULL,NULL,NULL,'인턴',1800000,0.012);
INSERT INTO EMPLOYEE
VALUES('132','김인창','windowMan','a1234','남','사당','010-1234-1262','인사',2100000,0.040);
INSERT INTO EMPLOYEE
VALUES('331','기다운','powerDown','a1234',NULL,'인천',NULL,'영업',2500000,0.038);
INSERT INTO EMPLOYEE
VALUES('332','최종군','finalGroup','a1234',NULL,'금천',NULL,'영업',2500000,0.038);
INSERT INTO EMPLOYEE
VALUES('012','이주원','migration1','a1234','여',NULL,NULL,'관리',2600000,0.055);

COMMIT;


-- 데이터 삭제 할때 DELET FROM 테이블명 WHERE 조건절;
SELECT * FROM EMPLOYEE;

